#!/bin/sh
#set -x
if [ ! -d "${EGTM_PRIV}" ] ; then
  SWD=`dirname $0` ; CWD=`pwd`
  cd ${SWD} ; SWD=`pwd` ; cd ${CWD}
  export EGTM_PRIV=${SWD}
fi

export EGTM_DATA=$(echo ${EGTM_PRIV}| awk -F'lib/egtm' '/lib\/egtm/{print $1"data"}')
A=$(echo ${EGTM_DATA}| grep "data$")
if [ -z "$A" ]; then 
	export EGTM_DATA=$(echo ${EGTM_PRIV}| awk -F'deps/egtm' '/deps\/egtm/{print $1"priv/data"}')
fi

export EGTM_TMP=/tmp

if [ -d ${EGTM_DATA} ]; then
   export EGTM_GBLS=${EGTM_DATA}/gbls
   mkdir -p ${EGTM_GBLS}
else
   export EGTM_DATA=${CWD}/priv/data
   export EGTM_GBLS=${EGTM_DATA}/gbls
   mkdir -p ${EGTM_DATA}
fi


export EGTM_CALLINTAB=${EGTM_PRIV}/calltab.ci

# Database files
export EGTM_DB_DEFAULT=${EGTM_GBLS}/egtm.dat
export EGTM_DB_BIG=${EGTM_GBLS}/egtmbig.dat

# Standard GT.M settings
export gtm_dist=/opt/fis-gtm/V6.0-003_x8664
export gtmroutines="${gtm_dist} ${EGTM_PRIV}/rtns ."
export gtmgbldir="${EGTM_GBLS}/egtm.gld"
export gtm_log=${EGTM_TMP}
export gtm_tmp=${EGTM_TMP}
export gtm_badchar="NO"
export gtm_noundef="YES"
export gtm_nocenable="YES"
export gtm_prompt="IDEA\$EGTM>"
export gtm_icu_version=5.2
export gtm_chset=UTF-8
export LC_CTYPE=en_US.UTF-8

# Detect UTF-8 environment
zchs=`echo ${gtm_chset} | tr '[:lower:]' '[:upper:]'`
if [ ${zchs:-""} = "UTF-8" ] ; then
  export gtm_dist="${gtm_dist}/utf8"
  export gtmroutines="${gtm_dist} ${gtmroutines}"
fi

# Application-specific environment
# script can be specified by setting
# the EGTM_CUSTOM_ENV environment variable
#
# NOTE: each of the customized variables
# must be re-exported to take effect
if [ -f ${EGTM_CUSTOM_ENV:-""} ] ; then
  . ${EGTM_CUSTOM_ENV}
fi
